# Trying to track down the conda env failures

name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: pyiron/actions/write-environment@use_miniconda
        with:
          env-files: .ci_support/environment.yml
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.12'
#          miniforge-variant: Miniforge3
#          miniforge-version: 'latest'
          channels: conda-forge
          conda-remove-defaults: 'true'
          channel-priority: strict
          activate-environment: my-env
          environment-file: ${{ env.WRITE_ENVIRONMENT_OUTPUT_ENV_FILE }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        shell: bash -l {0}
        run: |
          python -m unittest discover tests/unit